services:   

    api-gateway:
        container_name: api-gateway
        restart: always
        build:
            context: .
            dockerfile: Phonepay.Infrastructure/Gateway/Dockerfile
        ports:
            - "8081:8080"
        networks:
            - phonepay-network
            - default

    auth-service:
        container_name: auth-service
        restart: always
        build: 
            context: .
            dockerfile: Phonepay.Infrastructure/AuthService/Dockerfile
        depends_on:
            - api-gateway
        networks:
            - phonepay-network

    transaction-service:
        container_name: transaction-service
        restart: always
        build:
            context: .
            dockerfile: Phonepay.Infrastructure/TransactionService/Dockerfile
        depends_on:
            - transaction-database
            - api-gateway
        networks:
            - phonepay-network

    transaction-two-service:
        container_name: transaction-two-service
        restart: always
        build:
            context: .
            dockerfile: Phonepay.Infrastructure/TransactionService/Dockerfile
        depends_on:
            - transaction-database
            - api-gateway
        networks:
            - phonepay-network

    user-service:
        container_name: user-service
        restart: always
        build:
            context: .
            dockerfile: Phonepay.Infrastructure/UserService/Dockerfile
        depends_on:
            - user-database
            - api-gateway
        networks:
            - phonepay-network

    user-two-service:
        container_name: user-two-service
        restart: always
        build:
            context: .
            dockerfile: Phonepay.Infrastructure/UserService/Dockerfile
        depends_on:
            - user-database
            - api-gateway
        networks:
            - phonepay-network

    transaction-database:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: transaction-database
        restart: always
        environment:
            SA_PASSWORD: iLuvTransactions4ever<3
            ACCEPT_EULA: "Y"
        volumes:
            - ./data/transactiondb:/var/opt/mssql/data
        networks:
            - phonepay-network

    user-database:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: user-database
        restart: always
        environment:
            SA_PASSWORD: iLuvUsers4ever<3
            ACCEPT_EULA: "Y"
        volumes:
            - ./data/userdb:/var/opt/mssql/data
        networks:
            - phonepay-network

networks:
    phonepay-network:
        driver: bridge
        internal: true